ignore-uppercase-emojis: false
ignore-uppercase-emotes: false

emojis:
  ':skull:': ☠
  ':)': ツ
  ':rpg:': ⨷
  ':heart:': ❤
  '<3': ❤
  ':vitality:': ❤
  ':toughness:': 🛡
  ':strength:': 🗡
  ':dexterity:': 🏹
  ':mana:': ✦
  ':spirit:': ❖
  ':agility:': ➸
  ':attackspeed:': ↠
  ':critrate:': ⟴
  ':critdmg:': ⇉
  ':accuracy:': ↡
  ':gem:': ⥁
  ':aoedmg:': ⁐
  ':dodge:': ⅏
  ':bleed:': ∵
  ':block:': ⟁
  ':deflect:': ⟇
  ':healing:': ⧾
  ':damage:': ⚔
  ':coin:': ●
  ':floosh:': 🮯

emoji-hover: "&7<emoji>"

chat-message-format:
  enabled: true
  format: "{group} {name} &7>> {color}{message}"
  color:
    # permission node: sgcraft.chat.[group]
    default: "&r"
    '100': "&c"

damage-indicator:
  physical: "%original%"
  critical: "%original% &4X"

emotes:
  x: "&f{name} &7doubts."
  f: "&f{name} &7paid respects."
  y: "&f{name} &7shamed."
  sus: "&f{name}: &7thats kinda sus"

disable-spawning:
  armorsmith: true
  toolsmith: false
  weaponsmith: false
  zombie_villager: true

disable-block-interactions:
  - ENCHANTING_TABLE
  - LEGACY_ENCHANTMENT_TABLE
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - LEGACY_ANVIL
  - GRINDSTONE

disable-trades:
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS

despawn-vanilla-items:
  - DIAMOND_SWORD
  - DIAMOND_PICKAXE
  - DIAMOND_SHOVEL

disable-offhand:
  - DIAMOND_SWORD
  - IRON_SWORD
  - NETHERITE_SWORD
  - GOLDEN_SWORD
  - WOODEN_SWORD
  - STONE_SWORD
  - NETHERITE_AXE
  - DIAMOND_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - WOODEN_AXE
  - STONE_AXE
  - NETHERITE_HOE
  - DIAMOND_HOE
  - IRON_HOE
  - GOLDEN_HOE
  - STONE_HOE
  - WOODEN_HOE

lower-damage: {}

crit-format: "%original% &4-CRIT"

luckperms-expiry-commands:
  - /cmi nick off {player}